// ComChat.idl : IDL source for ComChat
//

// This file will be processed by the MIDL tool to
// produce the type library (ComChat.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

//
// struct ChatMessage - incapsulates a message
//

typedef struct {
	[ref]		BSTR		src;
	[unique]	BSTR		dst;		// may be NULL in case of a broadcast
	[ref]		BSTR		msg;

				FILETIME	time;		// message timestamp
} ChatMessage;

//
// IChatClient - client notification interface
//
[
	object,
	uuid(86BC549D-65A1-465C-9D36-4A5884757DC1),
	pointer_default(ref)
]
interface IChatClient : IUnknown {
	HRESULT notifyUserJoin([in,ref] BSTR name);
	HRESULT notifyUserLeave([in,ref] BSTR name);

	HRESULT notifyMessage([in,ref] ChatMessage* msg);
};

//
// IChatServerPort - chat server port
//
[
	object,
	uuid(F0A1DEEE-57D5-49DB-94F3-1BC126CB0B90),
	pointer_default(ref)
]
interface IChatServerPort : IUnknown {
	HRESULT sendMessage(
		[in, unique]	BSTR dest,
		[in, ref]		BSTR msg);
};

//
// IChatServer - chat server interface
//
[
	object,
	uuid(DBAFF0AF-038D-4924-A4DA-EF086EF356F3),
	pointer_default(ref)
]
interface IChatServer : IUnknown {
	HRESULT registerClient(
		[in,ref] BSTR name,
		[in] IChatClient* pClient,
		[out,retval] IChatServerPort** ppPort);
};

//
// library stuff
//

[
	uuid(6963B0F4-35B0-424E-B40F-97011A6C8037),
	version(1.0),
]
library ComChatLib
{
	importlib("stdole2.tlb");
	[
		uuid(180E422C-16E4-421C-BC12-0673D7B602A9)		
	]
	coclass ChatServer
	{
		[default] interface IChatServer;
	};
};

